#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = xconfig_hello
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/ti/xdctools_3_32_00_06_core/packages/xdc/utils.js:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/utils.js
C:/ti/xdctools_3_32_00_06_core/packages/xdc/xdc.tci:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/xdc.tci
C:/ti/xdctools_3_32_00_06_core/packages/xdc/template.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/template.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/om2.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/om2.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/xmlgen.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/xmlgen.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/xmlgen2.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/xmlgen2.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/Warnings.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/Warnings.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/IPackage.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/IPackage.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/package.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/package.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/services/global/Clock.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/services/global/Clock.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/services/global/Trace.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/services/global/Trace.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/bld.js:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/bld.js
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/BuildEnvironment.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/PackageContents.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/PackageContents.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/_gen.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/_gen.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Library.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Library.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Executable.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Executable.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Repository.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Repository.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Configuration.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Configuration.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Script.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Script.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Manifest.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Manifest.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Utils.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/Utils.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget2.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget2.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget3.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget3.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/ITargetFilter.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/package.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/bld/package.xs
package.mak: config.bld
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/ITarget.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/ITarget.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/_utils.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/_utils.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/Linux86.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/Linux86.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/Mingw.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/Mingw.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/package.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/package.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/ITarget.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/ITarget.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/GCArmv6.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/GCArmv7A.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/IM.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/IM.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/M3.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/M3.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/M4.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/M4.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/M4F.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/M4F.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/A8F.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/A8F.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/A9F.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/A9F.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/A15F.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/A15F.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/A53F.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/A53F.xs
C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/package.xs:
package.mak: C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/package.xs
package.mak: package.bld
C:/ti/xdctools_3_32_00_06_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
C:/ti/xdctools_3_32_00_06_core/packages/xdc/services/io/File.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/services/io/File.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/services/io/package.xs:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/services/io/package.xs
C:/ti/xdctools_3_32_00_06_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
C:/ti/xdctools_3_32_00_06_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
C:/ti/xdctools_3_32_00_06_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: C:/ti/xdctools_3_32_00_06_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

gnu.targets.arm.M4F.rootDir ?= C:/ti/ccsv7/tools/compiler/gcc-arm-none-eabi-4_9-2015q3
gnu.targets.arm.packageBase ?= C:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.om4fg
.PHONY: all,m4fg .dlls,m4fg .executables,m4fg test,m4fg
all,m4fg: .executables,m4fg
.executables,m4fg: .libraries,m4fg
.executables,m4fg: .dlls,m4fg
.dlls,m4fg: .libraries,m4fg
.libraries,m4fg: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,m4fg
	@$(ECHO) xdc .executables,m4fg
	@$(ECHO) xdc .libraries,m4fg
	@$(ECHO) xdc .dlls,m4fg


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_xconfig_hello.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package xconfig_hello" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,m4fg .dlls: hello.pm4fg

-include package/cfg/hello_pm4fg.mak
-include package/cfg/hello_pm4fg.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/hello_pm4fg.dep
endif
hello.pm4fg: package/cfg/hello_pm4fg.xdl
	@


ifeq (,$(wildcard .libraries,m4fg))
hello.pm4fg package/cfg/hello_pm4fg.c: .libraries,m4fg
endif

package/cfg/hello_pm4fg.c package/cfg/hello_pm4fg.h package/cfg/hello_pm4fg.xdl: override _PROG_NAME := hello.xm4fg
package/cfg/hello_pm4fg.c: package/cfg/hello_pm4fg.cfg
package/cfg/hello_pm4fg.xdc.inc: package/cfg/hello_pm4fg.xdl
package/cfg/hello_pm4fg.xdl package/cfg/hello_pm4fg.c: .interfaces

clean:: clean,m4fg
	-$(RM) package/cfg/hello_pm4fg.cfg
	-$(RM) package/cfg/hello_pm4fg.dep
	-$(RM) package/cfg/hello_pm4fg.c
	-$(RM) package/cfg/hello_pm4fg.xdc.inc

clean,m4fg::
	-$(RM) hello.pm4fg
.executables,m4fg .executables: hello.xm4fg

hello.xm4fg: |hello.pm4fg

-include package/cfg/hello.xm4fg.mak
hello.xm4fg: package/cfg/hello_pm4fg.om4fg 
	$(RM) $@
	@$(MSG) lnkm4fg $@ ...
	$(RM) $(XDCCFGDIR)$@.map
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -mthumb -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -nostartfiles -Wl,-static -Wl,--gc-sections     -LC:/ti/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/lib/armv7e-m/fpu  -o $@ package/cfg/hello_pm4fg.om4fg -Wl,-T,package/cfg/hello_pm4fg.xdl   -Wl,--start-group -lgcc -lc -lm -Wl,--end-group -Wl,-Map=$(XDCCFGDIR)/$@.map -Wl,--start-group -lnosys -Wl,--end-group
	
hello.xm4fg: export LD_LIBRARY_PATH=

hello.test test,m4fg test: hello.xm4fg.test

hello.xm4fg.test:: hello.xm4fg
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 hello.xm4fg.test
else
	@$(MSG) running $<  ...
	$(call EXEC.hello.xm4fg, ) 
endif

clean,m4fg::
	-$(RM) $(wildcard .tmp,hello.xm4fg,*)


clean:: clean,m4fg

clean,m4fg::
	-$(RM) hello.xm4fg
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
hello_pm4fg.om4fg,copy : package/cfg/hello_pm4fg.om4fg
hello_pm4fg.sm4fg,copy : package/cfg/hello_pm4fg.sm4fg

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,xconfig_hello
ifeq (,$(MK_NOGENDEPS))
-include package/rel/xconfig_hello.tar.dep
endif
package/rel/xconfig_hello/xconfig_hello/package/package.rel.xml: package/package.bld.xml
package/rel/xconfig_hello/xconfig_hello/package/package.rel.xml: package/build.cfg
package/rel/xconfig_hello/xconfig_hello/package/package.rel.xml: package/package.xdc.inc
package/rel/xconfig_hello/xconfig_hello/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

xconfig_hello.tar: package/rel/xconfig_hello.xdc.inc package/rel/xconfig_hello/xconfig_hello/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/xconfig_hello.xdc.inc,package/rel/xconfig_hello.tar.dep)


release release,xconfig_hello: all xconfig_hello.tar
clean:: .clean
	-$(RM) xconfig_hello.tar
	-$(RM) package/rel/xconfig_hello.xdc.inc
	-$(RM) package/rel/xconfig_hello.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
